export const GET_FAVORITES_LIST = "GET_FAVORITES_LIST";
export const ADD_ITEM_TO_FAVORITES_LIST = "ADD_ITEM_TO_FAVORITES_LIST";
export const REMOVE_ITEM_FROM_FAVORITES_LIST =
  "REMOVE_ITEM_FROM_FAVORITES_LIST";
